# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeChef.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle("")
        self.RecipeSearchString = QtWidgets.QTextEdit(Form)
        self.RecipeSearchString.setEnabled(True)
        self.RecipeSearchString.setGeometry(QtCore.QRect(250, 190, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        self.RecipeSearchString.setFont(font)
        self.RecipeSearchString.setStyleSheet("border-radius:50;")
        self.RecipeSearchString.setObjectName("RecipeSearchString")
        self.RecipeInformation = QtWidgets.QTextEdit(Form)
        self.RecipeInformation.setGeometry(QtCore.QRect(210, 290, 361, 171))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        self.RecipeInformation.setFont(font)
        self.RecipeInformation.setObjectName("RecipeInformation")
        self.CalorieInfo = QtWidgets.QGraphicsView(Form)
        self.CalorieInfo.setGeometry(QtCore.QRect(10, 470, 561, 121))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        self.CalorieInfo.setFont(font)
        self.CalorieInfo.setObjectName("CalorieInfo")
        self.ChefLogo = QtWidgets.QLabel(Form)
        self.ChefLogo.setGeometry(QtCore.QRect(-10, 30, 291, 271))
        self.ChefLogo.setStyleSheet("")
        self.ChefLogo.setText("")
        self.ChefLogo.setPixmap(QtGui.QPixmap(":/newPrefix/ChefLogo_NoBackground.png"))
        self.ChefLogo.setScaledContents(True)
        self.ChefLogo.setObjectName("ChefLogo")
        self.ChefLogo_2 = QtWidgets.QLabel(Form)
        self.ChefLogo_2.setGeometry(QtCore.QRect(200, -110, 441, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChefLogo_2.sizePolicy().hasHeightForWidth())
        self.ChefLogo_2.setSizePolicy(sizePolicy)
        self.ChefLogo_2.setMinimumSize(QtCore.QSize(441, 441))
        self.ChefLogo_2.setMaximumSize(QtCore.QSize(441, 441))
        self.ChefLogo_2.setSizeIncrement(QtCore.QSize(441, 441))
        self.ChefLogo_2.setBaseSize(QtCore.QSize(441, 441))
        self.ChefLogo_2.setText("")
        self.ChefLogo_2.setPixmap(QtGui.QPixmap(":/HomeCheflogo/homechef_Logo_NoBackground.png"))
        self.ChefLogo_2.setScaledContents(True)
        self.ChefLogo_2.setObjectName("ChefLogo_2")
        self.PleaseEnterLabel = QtWidgets.QLabel(Form)
        self.PleaseEnterLabel.setGeometry(QtCore.QRect(330, 190, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.PleaseEnterLabel.setFont(font)
        self.PleaseEnterLabel.setObjectName("PleaseEnterLabel")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 581, 601))
        self.label_2.setStyleSheet("background-image: url(:/BG/Untitled design.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/BG/Untitled design.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.searchButton = QtWidgets.QPushButton(Form)
        self.searchButton.setGeometry(QtCore.QRect(420, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setAutoFillBackground(False)
        self.searchButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 141, 2, 255), stop:0.507463 rgba(0, 167, 4, 255), stop:1 rgba(0, 139, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.searchButton.setText("SEARCH")
        self.searchButton.setFlat(False)
        self.searchButton.setObjectName("searchButton")
        self.ResetButton = QtWidgets.QPushButton(Form)
        self.ResetButton.setGeometry(QtCore.QRect(250, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ResetButton.setFont(font)
        self.ResetButton.setAutoFillBackground(False)
        self.ResetButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 141, 2, 255), stop:0.507463 rgba(0, 167, 4, 255), stop:1 rgba(0, 139, 0, 255));\n"
"color: rgb(255, 255, 255);")
        self.ResetButton.setText("RESET")
        self.ResetButton.setFlat(False)
        self.ResetButton.setObjectName("ResetButton")
        self.YoutubeLabel = QtWidgets.QLabel(Form)
        self.YoutubeLabel.setGeometry(QtCore.QRect(50, 280, 111, 61))
        self.YoutubeLabel.setStyleSheet("background-image: url(:/Youtube/youtube-logo-png-46020.png);")
        self.YoutubeLabel.setText("")
        self.YoutubeLabel.setPixmap(QtGui.QPixmap(":/Youtube/youtube-logo-png-46020.png"))
        self.YoutubeLabel.setScaledContents(True)
        self.YoutubeLabel.setObjectName("YoutubeLabel")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 290, 191, 171))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.RecipeLabel = QtWidgets.QLabel(Form)
        self.RecipeLabel.setGeometry(QtCore.QRect(360, 290, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecipeLabel.setFont(font)
        self.RecipeLabel.setObjectName("RecipeLabel")
        self.CalorieLabel = QtWidgets.QLabel(Form)
        self.CalorieLabel.setGeometry(QtCore.QRect(210, 470, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CalorieLabel.setFont(font)
        self.CalorieLabel.setObjectName("CalorieLabel")
        self.label_2.raise_()
        self.ChefLogo_2.raise_()
        self.RecipeSearchString.raise_()
        self.RecipeInformation.raise_()
        self.CalorieInfo.raise_()
        self.ChefLogo.raise_()
        self.PleaseEnterLabel.raise_()
        self.searchButton.raise_()
        self.ResetButton.raise_()
        self.textEdit.raise_()
        self.YoutubeLabel.raise_()
        self.RecipeLabel.raise_()
        self.CalorieLabel.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.PleaseEnterLabel.setText(_translate("Form", "Please enter a food item!"))
        self.RecipeLabel.setText(_translate("Form", "Recipe"))
        self.CalorieLabel.setText(_translate("Form", "Calorie Information"))

import Background_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

